cookie:
  expiry_days: 30
  key: ramus_ssuny_stock # Must be a string
  name: ramus
credentials:
  usernames:
    ramus:
      email: iam1492@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Ramus
      last_name: Jung
      logged_in: False # Will be managed automatically
      password: $2b$12$A3AN4h1ZS.t61s2ARbD17Oxyl/trjwf1le4rkGYlSruNinBDfZCre
      roles: # Optional
      - admin
    sunny:
      email: howtomeetme@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Sunny
      last_name: Park
      logged_in: False # Will be managed automatically
      password: $2b$12$eXfx.dLkvHb8KgkkPtK8LOL3zOmKrG2QNKYR6Z8EVcmr7rISPKxN2
      roles: # Optional
      - admin