cookie:
  expiry_days: 30
  key: ramus_ssuny_stock # Must be a string
  name: ramus
credentials:
  usernames:
    ramus:
      email: !ENV ${RAMUS_EMAIL}
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Ramus
      last_name: Jung
      logged_in: False # Will be managed automatically
      password: !ENV ${RAMUS_PW}
      roles: # Optional
      - admin
    sunny:
      email: !ENV ${SUNNY_EMAIL}
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Sunny
      last_name: Park
      logged_in: False # Will be managed automatically
      password: !ENV ${SUNNY_PW}
      roles: # Optional
      - viewer