research_task:
  description: >
    Gather and analyze the latest news and market sentinment surrounding 
    {company}'s stock. 
    Search information abount {company} from internet and retrieve recent important information.
    Use provided tools to get the latest news and market sentiment.
    Use ScrapeWebsiteTool and SerperDevTool to get the latest information about {company}
  expected_output: >
    Your final answer MUST be a detailed summary of the news and market 
    sentiment surrounding the stock.
  agent: researcher

financial_analysis_task:
  description: >
    Analyze the {company}'s financial statements, balance sheet, insider transactions data 
    and other metrics to evaluate {company}'s financial health and performance.
    Role of the financial analyst is:
    - Evaluating {company}'s value through financial statements and other metrics.
    - Building financial models to forecast future earnings and cash flow.
    - Conducting risk assessments by analyzing financial data.
    - Supporting investment and financing decisions.
    Using option chain data
    - Confirmation of investment sentiment through put/call ratio analysis.
    - Measurement of uncertainty through implied volatility.
    - Estimation of institutional investor position.
    Using the calulator tools to get the financial metrics and ratios.
    All the tools only need one ticker parameter which is {company}'s ticker name.
    Recommended to use all the provided tools to get enough financial data and metrics.
  expected_output: >
    Your final answer MUST be a detailed report with a {company}'s revenue, earnings,
    cash flow, option chain, and other key financial metrics.
  agent: financial_analyst

macro_strategist_task:
  description: >
    Analyze the USA economic environment, market trends, and global events 
    to provide insights on how they may impact the stock market and {company}'s stock in particular.
    • Develop sophisticated macro-economic frameworks to analyze global economic trends, monetary policies, and their impacts on financial markets
    • Generate high-conviction trade ideas and strategic investment recommendations across asset classes
    • Provide real-time analysis of market-moving economic data releases and central bank decisions
    • Present investment themes and market views to institutional clients and internal investment committees
    • Collaborate with cross-asset strategists to formulate cohesive investment strategies
    • Author flagship research publications and thematic reports on global macro trends
    Use the Macro Economic Analysis tool to analyze the USA economic environment, market trends, and global events that may impact the stock market and {company}'s stock in particular.
    - You can use the tool as many times as you want to get enough macroeconomic data and trends.
    - Use important series_id to get the data which is relevant to the macroeconomic analysis.
    for example, - GDPC1, UNRATE, GS10, T10Y2Y, M2, UMCSENT, CPIAUCNS, CPILFESL, PCEPI, PPIACO, RSXFS, INDPRO, HOUST, NHSLTOT, STLFSI3, 
  
  expected_output: >
    Your final answer MUST be a detailed report on the USA economic environment, market trends, 
    and global events that may impact the stock market and {company}'s stock in particular.
  agent: macro_strategist

technical_analysis_task:
  description: >
    Conduct a technical analysis of the {company} stock price movements 
    and identify key support and resistance levels chart patterns.
    When using the Stock Price tool
    - Use provided tool sequentially to analyze the stock price movements over different time frames.
    - parameter MUST be one word of {company}'s ticker name.(for example, ABNB, ONL, DIS, GRMN, BABA)
    - Stock Price - 1 Month tool to analyze the {company}'s stock price movements over the last month.
    - Stock Price - 1 Year tool to analyze the {company}'s stock price movements over the last year.

  expected_output: >
    Your final answer MUST be a report with potential entry points, 
    price targets and any other relevant information.
  agent: technical_analyst

investment_recommendation_task:
  description: >
    Based on the research, technical analysis, and financial analysis reports, 
    provide a detailed investment recommendation for {company} stock.
  expected_output: >
    Your final report MUST be a detailed recommendation to BUY, SELL or HOLD the stock.
    So final report MUST constain one of the RATING words, BUY, SELL or HOLD.
    Provide a clear and detailed rationale for your recommendation.
    The final answer MUST use markdown format for the best readability but don't wrap the content with ```markdown``` syntax.
  context: [research_task,technical_analysis_task,financial_analysis_task, macro_strategist_task]
  agent: hedge_fund_manager

translate_task:
  description: >
    Translate final report of hedge fund manager into korean language.
    But must not translate only the words, BUY, SELL, HOLD, leave them as English.
  expected_output: >
    Your final answer MUST be a translated version of the hedge fund manager's report in Korean.
  context: [investment_recommendation_task]
  agent: translator

intern_task:
  description: >
    Convert translated output to JSON object string using provided tool.
    You must pass the correct parameters to the provided tool - Report to JSON Converter
    Read the report carefully and pass the following parameters to the tool correctly.
    1. company:str - company name which is a string. 
    2. ticker:str - ticker of the company which is a string.
    3. rating:str - rating of the company which is a string. (example: Buy, Sell, Hold)
    4. final result:str - Full output of the translator. Before passing the output to the tool, you must convert the output to html formatting.
  expected_output: >
    Your final output MUST be a return value of the provided tool.
  context: [translate_task]
  agent: intern